SRCDIR    = $(BASEDIR)/src
INCDIR    = $(BASEDIR)/src

CXXFLAGS_BASE    = -I$(INCDIR)


HEADERS_BASE = \
    $(INCDIR)/Bittree_BitArray.h \
    $(INCDIR)/Bittree_Bits.h \
    $(INCDIR)/Bittree_BittreeAmr.h \
    $(INCDIR)/Bittree_MortonTree.h \
    $(INCDIR)/Bittree_Prelude.h \
    $(INCDIR)/Bittree_fi.h

SRCS_BASE    = \
    $(SRCDIR)/Bittree_BitArray.cpp \
    $(SRCDIR)/Bittree_MortonTree.cpp \
    $(srcdir)/Bittree_BittreeAmr.cpp \
    $(srcdir)/Bittree_fi.cpp
