SRCDIR    = $(BASEDIR)/src
INCDIR    = $(BASEDIR)/src

CXXFLAGS_BASE    = -I$(INCDIR)


HEADERS_BASE = \
    $(INCDIR)/Bittree_bitarray.h \
    $(INCDIR)/Bittree_bits.h \
    $(INCDIR)/Bittree_core.h \
    $(INCDIR)/Bittree_mortontree.h \
    $(INCDIR)/Bittree_prelude.h \
    $(INCDIR)/macros.h

SRCS_BASE    = \
    $(SRCDIR)/Bittree_bitarray.cpp \
    $(SRCDIR)/Bittree_mortontree.cpp \
    $(SRCDIR)/Bittree_core.cpp \
